# Generated by Django 6.0.3 on 2026-03-09 16:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('annual_revenue', models.IntegerField()),
                ('employee_count', models.IntegerField()),
                ('compliance_score', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['industry'], name='industry_idx'), models.Index(fields=['annual_revenue'], name='annual_revenue_idx'), models.Index(fields=['is_active'], name='is_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rank', models.IntegerField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceApp.company')),
            ],
            options={
                'indexes': [models.Index(fields=['total_score'], name='total_score_idx'), models.Index(fields=['rank'], name='rank_idx')],
            },
        ),
    ]
