# Generated by Django 6.0.3 on 2026-03-09 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='compliance_score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='companyscore',
            name='total_score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
