# Generated by Django 6.0.3 on 2026-03-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0002_alter_company_compliance_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyscore',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
